# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from nakode.v1 import nakode_pb2 as nakode_dot_v1_dot_nakode__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nakode/v1/nakode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NakodeServiceStub:
    """NakodeService is the complete product boundary used by every frontend.
    Watch methods emit authoritative replacement snapshots, not reducer events.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorkspace = channel.unary_unary(
                '/nakode.v1.NakodeService/GetWorkspace',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetWorkspaceRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.WorkspaceSnapshot.FromString,
                _registered_method=True)
        self.WatchWorkspace = channel.unary_stream(
                '/nakode.v1.NakodeService/WatchWorkspace',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.WatchWorkspaceRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.WorkspaceSnapshot.FromString,
                _registered_method=True)
        self.ReloadWorkspace = channel.unary_unary(
                '/nakode.v1.NakodeService/ReloadWorkspace',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.ReloadWorkspaceRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/nakode.v1.NakodeService/CreateSession',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/nakode.v1.NakodeService/OpenSession',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/nakode.v1.NakodeService/ListSessions',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/nakode.v1.NakodeService/GetSession',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.SessionSnapshot.FromString,
                _registered_method=True)
        self.WatchSession = channel.unary_stream(
                '/nakode.v1.NakodeService/WatchSession',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.WatchSessionRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.SessionSnapshot.FromString,
                _registered_method=True)
        self.SendPrompt = channel.unary_unary(
                '/nakode.v1.NakodeService/SendPrompt',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.SendPromptRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.EnqueuePrompt = channel.unary_unary(
                '/nakode.v1.NakodeService/EnqueuePrompt',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.EnqueuePromptRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.RemoveQueuedPrompt = channel.unary_unary(
                '/nakode.v1.NakodeService/RemoveQueuedPrompt',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.RemoveQueuedPromptRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.SteerTurn = channel.unary_unary(
                '/nakode.v1.NakodeService/SteerTurn',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.SteerTurnRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.CancelTurn = channel.unary_unary(
                '/nakode.v1.NakodeService/CancelTurn',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.CancelTurnRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.CancelSessionWork = channel.unary_unary(
                '/nakode.v1.NakodeService/CancelSessionWork',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.CancelSessionWorkRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.CompactContext = channel.unary_unary(
                '/nakode.v1.NakodeService/CompactContext',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.CompactContextRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.ResolveInteraction = channel.unary_unary(
                '/nakode.v1.NakodeService/ResolveInteraction',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.ResolveInteractionRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.RunShell = channel.unary_unary(
                '/nakode.v1.NakodeService/RunShell',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.RunShellRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.SelectModel = channel.unary_unary(
                '/nakode.v1.NakodeService/SelectModel',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.SelectModelRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.SetProviderEnabled = channel.unary_unary(
                '/nakode.v1.NakodeService/SetProviderEnabled',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.SetProviderEnabledRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.BeginProviderAuthentication = channel.unary_unary(
                '/nakode.v1.NakodeService/BeginProviderAuthentication',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.BeginProviderAuthenticationRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.SetProviderCredential = channel.unary_unary(
                '/nakode.v1.NakodeService/SetProviderCredential',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.SetProviderCredentialRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.ClearProviderCredential = channel.unary_unary(
                '/nakode.v1.NakodeService/ClearProviderCredential',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.ClearProviderCredentialRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.SaveAgent = channel.unary_unary(
                '/nakode.v1.NakodeService/SaveAgent',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.SaveAgentRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.DeleteAgent = channel.unary_unary(
                '/nakode.v1.NakodeService/DeleteAgent',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.DeleteAgentRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.UpdateSettings = channel.unary_unary(
                '/nakode.v1.NakodeService/UpdateSettings',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.UpdateSettingsRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.CheckAgentBrowser = channel.unary_unary(
                '/nakode.v1.NakodeService/CheckAgentBrowser',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.CheckAgentBrowserRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.Delegate = channel.unary_unary(
                '/nakode.v1.NakodeService/Delegate',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.DelegateRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/nakode.v1.NakodeService/ListRuns',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/nakode.v1.NakodeService/GetRun',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetRunRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.RunSnapshot.FromString,
                _registered_method=True)
        self.WatchRun = channel.unary_stream(
                '/nakode.v1.NakodeService/WatchRun',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.WatchRunRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.RunSnapshot.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/nakode.v1.NakodeService/CancelRun',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
                _registered_method=True)
        self.GetTranscriptPage = channel.unary_unary(
                '/nakode.v1.NakodeService/GetTranscriptPage',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetTranscriptPageRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.TranscriptPage.FromString,
                _registered_method=True)
        self.GetTranscriptBodyWindow = channel.unary_unary(
                '/nakode.v1.NakodeService/GetTranscriptBodyWindow',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetTranscriptBodyWindowRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.TranscriptBodyWindow.FromString,
                _registered_method=True)
        self.GetRunTextWindow = channel.unary_unary(
                '/nakode.v1.NakodeService/GetRunTextWindow',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetRunTextWindowRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.RunTextWindow.FromString,
                _registered_method=True)
        self.GetArtifact = channel.unary_unary(
                '/nakode.v1.NakodeService/GetArtifact',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetArtifactRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.Artifact.FromString,
                _registered_method=True)
        self.GetDiagnostics = channel.unary_unary(
                '/nakode.v1.NakodeService/GetDiagnostics',
                request_serializer=nakode_dot_v1_dot_nakode__pb2.GetDiagnosticsRequest.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.DiagnosticsReport.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/nakode.v1.NakodeService/GetServerInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=nakode_dot_v1_dot_nakode__pb2.ServerInfo.FromString,
                _registered_method=True)


class NakodeServiceServicer:
    """NakodeService is the complete product boundary used by every frontend.
    Watch methods emit authoritative replacement snapshots, not reducer events.
    """

    def GetWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueuePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveQueuedPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SteerTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSessionWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompactContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveInteraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunShell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProviderEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginProviderAuthentication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProviderCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearProviderCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAgentBrowser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delegate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTranscriptPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTranscriptBodyWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunTextWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NakodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetWorkspaceRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.WorkspaceSnapshot.SerializeToString,
            ),
            'WatchWorkspace': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchWorkspace,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.WatchWorkspaceRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.WorkspaceSnapshot.SerializeToString,
            ),
            'ReloadWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadWorkspace,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.ReloadWorkspaceRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.CreateSessionRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.OpenSessionRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.ListSessionsRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.ListSessionsResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetSessionRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.SessionSnapshot.SerializeToString,
            ),
            'WatchSession': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSession,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.WatchSessionRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.SessionSnapshot.SerializeToString,
            ),
            'SendPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrompt,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.SendPromptRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'EnqueuePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueuePrompt,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.EnqueuePromptRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'RemoveQueuedPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveQueuedPrompt,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.RemoveQueuedPromptRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'SteerTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.SteerTurn,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.SteerTurnRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'CancelTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTurn,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.CancelTurnRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'CancelSessionWork': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSessionWork,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.CancelSessionWorkRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'CompactContext': grpc.unary_unary_rpc_method_handler(
                    servicer.CompactContext,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.CompactContextRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'ResolveInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveInteraction,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.ResolveInteractionRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'RunShell': grpc.unary_unary_rpc_method_handler(
                    servicer.RunShell,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.RunShellRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'SelectModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectModel,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.SelectModelRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'SetProviderEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProviderEnabled,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.SetProviderEnabledRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'BeginProviderAuthentication': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginProviderAuthentication,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.BeginProviderAuthenticationRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'SetProviderCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProviderCredential,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.SetProviderCredentialRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'ClearProviderCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearProviderCredential,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.ClearProviderCredentialRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'SaveAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveAgent,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.SaveAgentRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'DeleteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAgent,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.DeleteAgentRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'UpdateSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSettings,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.UpdateSettingsRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'CheckAgentBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAgentBrowser,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.CheckAgentBrowserRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'Delegate': grpc.unary_unary_rpc_method_handler(
                    servicer.Delegate,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.DelegateRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.ListRunsRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.ListRunsResponse.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetRunRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.RunSnapshot.SerializeToString,
            ),
            'WatchRun': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRun,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.WatchRunRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.RunSnapshot.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.CancelRunRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.MutationResult.SerializeToString,
            ),
            'GetTranscriptPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscriptPage,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetTranscriptPageRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.TranscriptPage.SerializeToString,
            ),
            'GetTranscriptBodyWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscriptBodyWindow,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetTranscriptBodyWindowRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.TranscriptBodyWindow.SerializeToString,
            ),
            'GetRunTextWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunTextWindow,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetRunTextWindowRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.RunTextWindow.SerializeToString,
            ),
            'GetArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifact,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetArtifactRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.Artifact.SerializeToString,
            ),
            'GetDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiagnostics,
                    request_deserializer=nakode_dot_v1_dot_nakode__pb2.GetDiagnosticsRequest.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.DiagnosticsReport.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=nakode_dot_v1_dot_nakode__pb2.ServerInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nakode.v1.NakodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nakode.v1.NakodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NakodeService:
    """NakodeService is the complete product boundary used by every frontend.
    Watch methods emit authoritative replacement snapshots, not reducer events.
    """

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetWorkspace',
            nakode_dot_v1_dot_nakode__pb2.GetWorkspaceRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.WorkspaceSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nakode.v1.NakodeService/WatchWorkspace',
            nakode_dot_v1_dot_nakode__pb2.WatchWorkspaceRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.WorkspaceSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/ReloadWorkspace',
            nakode_dot_v1_dot_nakode__pb2.ReloadWorkspaceRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/CreateSession',
            nakode_dot_v1_dot_nakode__pb2.CreateSessionRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/OpenSession',
            nakode_dot_v1_dot_nakode__pb2.OpenSessionRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/ListSessions',
            nakode_dot_v1_dot_nakode__pb2.ListSessionsRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetSession',
            nakode_dot_v1_dot_nakode__pb2.GetSessionRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.SessionSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nakode.v1.NakodeService/WatchSession',
            nakode_dot_v1_dot_nakode__pb2.WatchSessionRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.SessionSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/SendPrompt',
            nakode_dot_v1_dot_nakode__pb2.SendPromptRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueuePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/EnqueuePrompt',
            nakode_dot_v1_dot_nakode__pb2.EnqueuePromptRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveQueuedPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/RemoveQueuedPrompt',
            nakode_dot_v1_dot_nakode__pb2.RemoveQueuedPromptRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SteerTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/SteerTurn',
            nakode_dot_v1_dot_nakode__pb2.SteerTurnRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/CancelTurn',
            nakode_dot_v1_dot_nakode__pb2.CancelTurnRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSessionWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/CancelSessionWork',
            nakode_dot_v1_dot_nakode__pb2.CancelSessionWorkRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompactContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/CompactContext',
            nakode_dot_v1_dot_nakode__pb2.CompactContextRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/ResolveInteraction',
            nakode_dot_v1_dot_nakode__pb2.ResolveInteractionRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunShell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/RunShell',
            nakode_dot_v1_dot_nakode__pb2.RunShellRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/SelectModel',
            nakode_dot_v1_dot_nakode__pb2.SelectModelRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProviderEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/SetProviderEnabled',
            nakode_dot_v1_dot_nakode__pb2.SetProviderEnabledRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginProviderAuthentication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/BeginProviderAuthentication',
            nakode_dot_v1_dot_nakode__pb2.BeginProviderAuthenticationRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProviderCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/SetProviderCredential',
            nakode_dot_v1_dot_nakode__pb2.SetProviderCredentialRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearProviderCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/ClearProviderCredential',
            nakode_dot_v1_dot_nakode__pb2.ClearProviderCredentialRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/SaveAgent',
            nakode_dot_v1_dot_nakode__pb2.SaveAgentRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/DeleteAgent',
            nakode_dot_v1_dot_nakode__pb2.DeleteAgentRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/UpdateSettings',
            nakode_dot_v1_dot_nakode__pb2.UpdateSettingsRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAgentBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/CheckAgentBrowser',
            nakode_dot_v1_dot_nakode__pb2.CheckAgentBrowserRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delegate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/Delegate',
            nakode_dot_v1_dot_nakode__pb2.DelegateRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/ListRuns',
            nakode_dot_v1_dot_nakode__pb2.ListRunsRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetRun',
            nakode_dot_v1_dot_nakode__pb2.GetRunRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.RunSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nakode.v1.NakodeService/WatchRun',
            nakode_dot_v1_dot_nakode__pb2.WatchRunRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.RunSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/CancelRun',
            nakode_dot_v1_dot_nakode__pb2.CancelRunRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.MutationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTranscriptPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetTranscriptPage',
            nakode_dot_v1_dot_nakode__pb2.GetTranscriptPageRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.TranscriptPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTranscriptBodyWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetTranscriptBodyWindow',
            nakode_dot_v1_dot_nakode__pb2.GetTranscriptBodyWindowRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.TranscriptBodyWindow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunTextWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetRunTextWindow',
            nakode_dot_v1_dot_nakode__pb2.GetRunTextWindowRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.RunTextWindow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetArtifact',
            nakode_dot_v1_dot_nakode__pb2.GetArtifactRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetDiagnostics',
            nakode_dot_v1_dot_nakode__pb2.GetDiagnosticsRequest.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.DiagnosticsReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nakode.v1.NakodeService/GetServerInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            nakode_dot_v1_dot_nakode__pb2.ServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
